### PR TITLE
#337/2/UI/Desktop/Footer desktop fix

### PR DESCRIPTION
**Pull request by RobertS-ki**
Changed max-width to 1620px and added margin-top: 1rem. Also Nav small fixes included: width 1620px, removed one navlink, fixed positioning on landingPage, fix background on landingPage. Removed "zarejestruj się" or "zaloguj" button when its duplicate on the page.
obraz

### CODE REVIEW

**Comment by vieraboschkova** [comment]
Add build please :)

**Comment by RobertS-ki** [comment]
> Add build please :)

Added build.

**Comment by n0macx** [comment]
image
Maybe it would be nicer positioning ?

**Comment by RobertS-ki** [comment]
> 

Even better

**Comment by RobertS-ki** [comment]
> 

Even better 
obraz

**Review by n0macx — APPROVED** [review]
Good Job

**Pull request merged**
