### PR TITLE
#104/PART2/UI/ - Added input errors red border

### PR DESCRIPTION
**Pull request by n0macx**
Added input errors red border

### CODE REVIEW

**Review by MonikaKrella — COMMENTED** [review]
image
is it a proper view?
TODO - to think - maybe as another issue - to almost every inputs validation runs when i check checkbox and click button. Maybe there is possibility to validate inputs when focus goes away from current input?

**Review by MonikaKrella — COMMENTED** [review]
image
is it proper result?
There is also i think one more issue - before clicking checkbox

**Comment by n0macx** [comment]
> small bugfix todo - now validation for name is at least 4 characters, but there is name Ewa with 3 :)

My ex is Ewa and i need to be shure she won't be allowed to register in our app ;).

**Comment by n0macx** [comment]
> image is it a proper view? TODO - to think - maybe as another issue - to almost every inputs validation runs when i check checkbox and click button. Maybe there is possibility to validate inputs when focus goes away from current input?

Its doable but i feel like going back and forth. Maybe ill just make it a TODO if there will be time ?

**Review by MonikaKrella — APPROVED** [review]
good job!
TODO PART 3 - error handling

**Pull request merged**
